### PR TITLE
Added timestamp to logger

### PR DESCRIPTION
**Pull request by theCyberTech**
Updated the logger.py file to include timestamps when logging output. For example:

 [2024-05-20 15:32:48][DEBUG]: == Working Agent: Researcher
 [2024-05-20 15:32:48][INFO]: == Starting Task: Research the topic
 [2024-05-20 15:33:22][DEBUG]: == [Researcher] Task output:

### CODE REVIEW

**Review by pythonbyte — APPROVED** [review]
LGTM. Nice!

**Comment by theCyberTech** [comment]
Apologies, had to revert an unrelated commit here

**Review by joaomdmoura — APPROVED** [review]
<3

**Comment by gabriels1234** [comment]
@joaomdmoura 
import datetime?

 timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')

**Comment by joaomdmoura** [comment]
Good catch, just got the error online

**Comment by theCyberTech** [comment]
Sorry,  I forget to add the datetime module

**Pull request merged**
