### PR TITLE
Allow to use async tools within the task pipeline

### PR DESCRIPTION
**Pull request by tg1482**
Introduces a way to use async tools seamlessly within a crew task.

### CODE REVIEW

**Comment by joaomdmoura** [comment]
Interesting, would love to hear more about the use case that prompted this given the `async_exec` attribute on task :)

**Comment by joaomdmoura** [comment]
link for reference: https://docs.crewai.com/core-concepts/Tasks/#asynchronous-execution

**Comment by tg1482** [comment]
Wow thanks for your promptness. One of the things we wanted to do was to give the agents the ability to talk to the users to ask clarifying questions directly using the websockets that we provide them. So we made a tool that allows the agent to ask questions and wait for a response from the user. But we don't want to exit the task pipeline since that will take a little longer + more openai api calls. 

This is also helpful for some tools where the agent prepares a draft email for instance, but wants to wait for the user confirmation before proceeding to send it. The tool has to await a response before proceeding - so this async allows for that. Its not just for the task to be async, but rather the Tools to be async.

**Comment by joaomdmoura** [comment]
Oh got it, something more complex then the current [human input on execution](https://docs.crewai.com/how-to/Human-Input-on-Execution/)? basically that but over sockets.
I assume in this case the new task could be processed while the current one awaits the input?

**Comment by tg1482** [comment]
Yes exactly - we can do as many new tasks while waiting for a response on a previous task.

**Comment by joaomdmoura** [comment]
got it! Any chance you would make this socket human input tool public? :D no pressure but I'd love to add it to crewai-tool or find a way to bring them into the main package somehow

**Comment by joaomdmoura** [comment]
This is a big change so I'll test is a little myself before merging just in case but I like the problem it aims to solve

**Comment by tg1482** [comment]
Amazing - appreciate any feedback on it and ideas on how to make the code a little less redundant - since most of it is just about adding an await in the right places. And detecting whether the tool is a coroutine or not and then deciding to use _run or await _run.

**Comment by tg1482** [comment]
And certainly, I'll try and add the socket human input in a following PR but that part is a little more coupled with my current infra setup haha so could be tough. But I agree, would be a great addition to the crewai toolkit

**Comment by tg1482** [comment]
I've added a quick `crew_test` but I'm unable to get it to run locally. But hopefully it'll be quick enough for you to take a look + adding some resiliency! Thanks again! Please let me know if I can help in any way!

**Comment by davidlandais** [comment]
Hello! I just came across this MR. I found out about CrewAI from a video on agentic workflow. I'm also interested in being able to intervene during a workflow. I prefer that the AI asks me questions, probes me so that I myself can be an agent influencing the final outcome. Have you considered using messaging tools like Slack, Discord, or Telegram? I assume your websocket tool is homemade? Would a workflow that uses a database to save its state to resume its process later be an interesting topic to explore for CrewAI?

**Comment by thehapyone** [comment]
I think this native support for async will be really nice to have considering most of the LLM already supports this. I was hoping to integrate CrewAI has the Agent framework for Sage https://github.com/thehapyone/Sage
but the lack of async support is a bit blocking. 

Alternatively, asyncify is one hack package that can be used to create a sync version of this

**Comment by tg1482** [comment]
Creating a new PR with a lot fewer changes to the code base.

**Pull request closed without merging**
