### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by siddartha-10**
Added the Example of using Human as a Tool as mentioned in issue #55

### CODE REVIEW

**Comment by joaomdmoura** [comment]
Hey @siddartha-10 I really like this but after checking the README I think it's getting too packed, do you mind if we move this to the wiki and maybe just link it on the README under the examples section?

**Comment by siddartha-10** [comment]
Hey @joaomdmoura Can you help me add this example to wiki because i am not able to clone it.
Can you help me with that and also let me know how do i link it from README to the wiki examples.

**Comment by joaomdmoura** [comment]
sure, doing it right now

**Comment by siddartha-10** [comment]
Hey i have to add it to the agentTools in wiki?

**Comment by joaomdmoura** [comment]
I went ahead I jsut added it to the wiki and readme, added an example based on the original on on the readme: https://github.com/joaomdmoura/crewAI/wiki/Human-Input-on-Execution

**Comment by siddartha-10** [comment]
That's great i wanted to contribute to crewAI is there any way we can connect and you can guide me?

**Comment by scenaristeur** [comment]
hi  ```from langchain.agents import load_tool``` is missing in https://github.com/joaomdmoura/crewAI/wiki/Human-Input-on-Execution

**Pull request closed without merging**
